//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsToBecomeAuthor
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Message { get; set; }
        public bool isClose { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
