//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryUP11Entities : DbContext
    {
        public LibraryUP11Entities()
            : base("name=LibraryUP11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationsToBecomeAuthor> ApplicationsToBecomeAuthor { get; set; }
        public virtual DbSet<ApplicationsToUnfreeze> ApplicationsToUnfreeze { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BookStatus> BookStatus { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<ReadingList> ReadingList { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<ReportType> ReportType { get; set; }
    }
}
